actions:
  1:
    action: delete_indices
    description: >-
      Delete indices larger than 2GB (based on idex name), for os-*
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: True
    filters:
    - filtertype: pattern
      kind: prefix
      value: os-
    - filtertype: space
      disk_space: 2
      use_age: True
      source: field_stats
      field: '@timestamp'
      stats_result: max_value
